vich_uploader:
    db_driver: orm

    mappings:
        movies:
            uri_prefix: /uploads/images/movies
            upload_destination: '%kernel.project_dir%/public/uploads/images/movies'
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
